//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EIRS.BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentRuleRollover
    {
        public int AssessmentRuleID { get; set; }
        public string AssessmentRuleCode { get; set; }
        public Nullable<int> ProfileID { get; set; }
        public string AssessmentRuleName { get; set; }
        public Nullable<int> RuleRunID { get; set; }
        public Nullable<int> PaymentFrequencyID { get; set; }
        public Nullable<decimal> AssessmentAmount { get; set; }
        public Nullable<int> TaxYear { get; set; }
        public Nullable<int> TaxMonth { get; set; }
        public Nullable<int> PaymentOptionID { get; set; }
        public Nullable<int> Activebit { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
